import oop.parcial2.neighborhood.*;
import java.util.Arrays;
public class Main {
    public  static void main(String[] args) {
        Neighborhood neighborhood = Neighborhood.builder()
        .streets(Arrays.asList(
                Street.builder()
                        .name("Street 1")
                        .houses(100, House.builder()
                                .kitchen(Kitchen.builder()
                                        .oven(false)
                                        .width(90)
                                        .height(20)
                                        .color("White and grey")
                                        .sink(false)
                                        .stove(true)
                                        .build())
                                .bedRoom(BedRoom.builder()
                                        .bedSize(BedSize.king)
                                        .color("Blue")
                                        .height(15)
                                        .width(60)
                                        .tv(false)
                                        .build())
                                .diningRoom(DiningRoom.builder()
                                        .tv(true)
                                        .chairsCapacity(8)
                                        .windows(10)
                                        .width(100)
                                        .height(10)
                                        .color("Red")
                                        .build())
                                .build())
                        .houses(101, House.builder()
                                .kitchen(Kitchen.builder()
                                        .oven(false)
                                        .width(90)
                                        .height(20)
                                        .color("White and grey")
                                        .sink(false)
                                        .stove(true)
                                        .build())
                                .bedRoom(BedRoom.builder()
                                        .bedSize(BedSize.matrimonial)
                                        .color("Blue")
                                        .height(15)
                                        .width(60)
                                        .tv(false)
                                        .build())
                                .diningRoom(DiningRoom.builder()
                                        .tv(true)
                                        .chairsCapacity(8)
                                        .windows(10)
                                        .width(100)
                                        .height(10)
                                        .color("Red")
                                        .build())
                                .build())
                        .build(),
                Street.builder()
                        .name("Street 2")
                        .houses(103, House.builder()
                                .kitchen(Kitchen.builder()
                                        .oven(false)
                                        .width(90)
                                        .height(20)
                                        .color("White and grey")
                                        .sink(false)
                                        .stove(true)
                                        .build())
                                .bedRoom(BedRoom.builder()
                                        .bedSize(BedSize.individual)
                                        .color("Blue")
                                        .height(15)
                                        .width(60)
                                        .tv(false)
                                        .build())
                                .diningRoom(DiningRoom.builder()
                                        .tv(true)
                                        .chairsCapacity(8)
                                        .windows(10)
                                        .width(100)
                                        .height(10)
                                        .color("Red")
                                        .build())
                                .build())
                        .houses(104, House.builder()
                                .kitchen(Kitchen.builder()
                                        .oven(false)
                                        .width(90)
                                        .height(20)
                                        .color("White and grey")
                                        .sink(false)
                                        .stove(true)
                                        .build())
                                .bedRoom(BedRoom.builder()
                                        .bedSize(BedSize.queen)
                                        .color("Blue")
                                        .height(15)
                                        .width(60)
                                        .tv(false)
                                        .build())
                                .diningRoom(DiningRoom.builder()
                                        .tv(true)
                                        .chairsCapacity(8)
                                        .windows(10)
                                        .width(100)
                                        .height(10)
                                        .color("Red")
                                        .build())
                                .build())
                        .build()))
                .gardens(2)
                .basketballCourt(true)
                .swimmingPool(true)
                .build();
    }
}
